# name: Hello world

# # on: [push, workflow_dispatch]\

# on:
#   push:
#     branches:
#       - main
#       - 'feature/**'
#     paths-ignore:
#       - '.github/workflows/**'
#       - README.md
#   workflow_dispatch:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v4

#       - name: Install Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Cache Dependencies
#         uses: actions/cache@v4
#         with: 
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
#           restore-keys: |
#             ${{ runner.os }}-npm-

#       - name: Install Dependencies
#         run: npm ci

#       - name: Build App
#         run: npm run build  # Ensure you have "build" script in package.json

#       - name: Run Tests
#         run: npm run test
  
#   build:
#     needs: test
#     runs-on: ubuntu-latest
#     steps: 
#         - name: Get Code
#           uses: actions/checkout@v4

#         - name: Install Node
#           uses: actions/setup-node@v4
#           with:
#             node-version: 20

#         - name: Reuse NPM cache
#           uses: actions/cache@v4
#           with:
#             path: ~/.npm
#             key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#             restore-keys: |
#               ${{ runner.os }}-npm-

#         - name: Install Dependencies
#           run: npm ci

#         - name: Build App
#           run: npm run build
#         - name: Artifact-Upload
#           uses: actions/upload-artifact@v4
#           with: 
#             name: dist-files
#             path: dist


#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Artifact-Upload
#         uses: actions/download-artifact@v4
#         with: 
#             name: dist-files
#             path: dist
#       - name: Deploy
#         run: echo "Deploying App"
#              echo "Deployment successfull"

            

#       # - name: Get Code
#       #   uses: actions/checkout@v4

#       # - name: Install Node
#       #   uses: actions/setup-node@v4
#       #   with:
#       #     node-version: 20

#       # - name: Reuse NPM cache
#       #   uses: actions/cache@v4
#       #   with:
#       #     path: ~/.npm
#       #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#       #     restore-keys: |
#       #       ${{ runner.os }}-npm-

#       # - name: Install Dependencies
#       #   run: npm ci

#       # - name: Build App
#       #   run: npm run build

#       # - name: Deploy step (demo)
#       #   run: |
#       #     echo "Deploying the app..."
#       #     if [ -d build ]; then
#       #       ls -l build
#       #     else
#       #       echo "⚠️ Warning: No build directory found."
#       #     fi
#       #     echo "Deployment successful"



  

 